name: mistake_collection
description: 错题分类及推荐APP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # 状态管理
  provider: ^6.1.1
  
  # 数据库
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # 图片处理
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # HTTP请求
  http: ^1.1.0
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # 权限处理
  permission_handler: ^11.0.1
  
  # UI组件
  flutter_staggered_grid_view: ^0.7.0
  expandable: ^5.0.1
  
  # 日期时间
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 